// Autogenerated from Pigeon (v10.1.6), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class RegistrationSubmitResponse;

@interface RegistrationSubmitResponse : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithRId:(NSString *)rId
    errorCode:(nullable NSString *)errorCode;
@property(nonatomic, copy) NSString * rId;
@property(nonatomic, copy, nullable) NSString * errorCode;
@end

/// The codec used by RegistrationDataApi.
NSObject<FlutterMessageCodec> *RegistrationDataApiGetCodec(void);

@protocol RegistrationDataApi
- (void)startRegistrationLanguages:(NSArray<NSString *> *)languages flowType:(NSString *)flowType process:(NSString *)process completion:(void (^)(NSString *_Nullable, FlutterError *_Nullable))completion;
- (void)evaluateMVELVisibleFieldData:(NSString *)fieldData completion:(void (^)(NSNumber *_Nullable, FlutterError *_Nullable))completion;
- (void)evaluateMVELRequiredFieldData:(NSString *)fieldData completion:(void (^)(NSNumber *_Nullable, FlutterError *_Nullable))completion;
- (void)getPreviewTemplateIsPreview:(NSNumber *)isPreview templateValues:(NSDictionary<NSString *, NSString *> *)templateValues completion:(void (^)(NSString *_Nullable, FlutterError *_Nullable))completion;
- (void)submitRegistrationDtoMakerName:(NSString *)makerName completion:(void (^)(RegistrationSubmitResponse *_Nullable, FlutterError *_Nullable))completion;
@end

extern void RegistrationDataApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<RegistrationDataApi> *_Nullable api);

NS_ASSUME_NONNULL_END
