// Autogenerated from Pigeon (v10.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class LocationResponse;

@interface LocationResponse : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithCountryList:(NSArray<NSString *> *)countryList
    regionList:(NSArray<NSString *> *)regionList
    provinceList:(NSArray<NSString *> *)provinceList
    cityList:(NSArray<NSString *> *)cityList
    zoneList:(NSArray<NSString *> *)zoneList
    postalCodeList:(NSArray<NSString *> *)postalCodeList;
@property(nonatomic, strong) NSArray<NSString *> * countryList;
@property(nonatomic, strong) NSArray<NSString *> * regionList;
@property(nonatomic, strong) NSArray<NSString *> * provinceList;
@property(nonatomic, strong) NSArray<NSString *> * cityList;
@property(nonatomic, strong) NSArray<NSString *> * zoneList;
@property(nonatomic, strong) NSArray<NSString *> * postalCodeList;
@end

/// The codec used by LocationResponseApi.
NSObject<FlutterMessageCodec> *LocationResponseApiGetCodec(void);

@protocol LocationResponseApi
- (void)fetchLocationListLangCode:(NSString *)langCode hierarchyName:(NSArray<NSString *> *)hierarchyName completion:(void (^)(LocationResponse *_Nullable, FlutterError *_Nullable))completion;
@end

extern void LocationResponseApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<LocationResponseApi> *_Nullable api);

NS_ASSUME_NONNULL_END
