package regclient.utils;

import java.lang.reflect.Field;
import java.util.List;
import java.util.Map;

import javax.ws.rs.core.MediaType;

import org.apache.log4j.Level;
import org.apache.log4j.Logger;
import org.testng.ITest;
import org.testng.ITestContext;
import org.testng.ITestResult;
import org.testng.Reporter;
import org.testng.SkipException;
import org.testng.annotations.AfterClass;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;
import org.testng.internal.BaseTestMethod;
import org.testng.internal.TestResult;

import regclient.api.ArcConfigManager;
import regclient.utils.TestDataReader;
import io.mosip.testrig.apirig.dto.OutputValidationDto;
import io.mosip.testrig.apirig.dto.TestCaseDTO;
import io.mosip.testrig.apirig.testrunner.HealthChecker;
import io.mosip.testrig.apirig.testrunner.JsonPrecondtion;
import io.mosip.testrig.apirig.utils.AdminTestException;
import io.mosip.testrig.apirig.utils.AdminTestUtil;
import io.mosip.testrig.apirig.utils.AuthenticationTestException;
import io.mosip.testrig.apirig.utils.GlobalConstants;
import io.mosip.testrig.apirig.utils.KernelAuthentication;
import io.mosip.testrig.apirig.utils.OutputValidationUtil;
import io.mosip.testrig.apirig.utils.ReportUtil;
import io.mosip.testrig.apirig.utils.RestClient;
import io.mosip.testrig.apirig.utils.SecurityXSSException;
import io.restassured.response.Response;

public class GenerateUinFromAid extends AdminTestUtil implements ITest {

	private static final Logger logger = Logger.getLogger(GenerateUinFromAid.class);
	protected String testCaseName = "";
	public Response response = null;

	private static final String IDREPO_RID_ENDPOINT = "/v1/idrepository/v1/identity/rid/";
	private static final String RESPONSE_IDENTITY_UIN = "response.identity.UIN";
	private static final String AID_PREFIX = "AID-";
	private static final int MAX_RETRIES = 5;
	private static final int WAIT_SECONDS = 10;

	@Override
	public String getTestName() {
		return testCaseName;
	}

	@BeforeClass
	public static void setLogLevel() {
		if (ArcConfigManager.IsDebugEnabled())
			logger.setLevel(Level.ALL);
		else
			logger.setLevel(Level.ERROR);
	}

	@DataProvider(name = "testcaselist")
	public Object[] getTestCaseList(ITestContext context) {
		String ymlFile = context.getCurrentXmlTest().getLocalParameters().get("ymlFile");
		logger.info("Started executing yml: " + ymlFile);
		return getYmlTestData(ymlFile);
	}

	@Test(dataProvider = "testcaselist")
	public void test(TestCaseDTO testCaseDTO)
			throws AuthenticationTestException, AdminTestException, SecurityXSSException, InterruptedException {

		testCaseName = testCaseDTO.getTestCaseName();

		if (HealthChecker.signalTerminateExecution) {
			throw new SkipException(
					GlobalConstants.TARGET_ENV_HEALTH_CHECK_FAILED + HealthChecker.healthCheckFailureMapS);
		}

		testCaseDTO.setInputTemplate(AdminTestUtil.modifySchemaGenerateHbs(testCaseDTO.isRegenerateHbs()));

		String aid = TestDataReader.readData("AID");
		if (aid == null || aid.isBlank() || !aid.startsWith(AID_PREFIX)) {
			throw new AdminTestException("Invalid or missing AID in testdata.json: " + aid);
		}
		String rid = aid.substring(AID_PREFIX.length());
		logger.info("AID and RID generated successfully");

		String token = new KernelAuthentication().getTokenByRole(testCaseDTO.getRole());
		String uin = fetchUINWithRetry(rid, token);

		if (uin == null || uin.isEmpty()) {
			throw new AdminTestException("UIN not generated for AID [" + aid + "] after " + MAX_RETRIES + " retries");
		}

		TestDataReader.saveData("UIN", uin);
		logger.info("UIN persisted: " + uin);

		String inputJson = getJsonFromTemplate(testCaseDTO.getInput(), testCaseDTO.getInputTemplate(), false);
		inputJson = inputJson.replace("$UIN$", uin);
		inputJson = inputJson.replace("$RID$", rid);

		response = postWithBodyAndCookie(ApplnURI + testCaseDTO.getEndPoint(), inputJson, COOKIENAME,
				testCaseDTO.getRole(), testCaseDTO.getTestCaseName());

		Map<String, List<OutputValidationDto>> ouputValid = OutputValidationUtil.doJsonOutputValidation(
				response.asString(), getJsonFromTemplate(testCaseDTO.getOutput(), testCaseDTO.getOutputTemplate()),
				testCaseDTO, response.getStatusCode());

		Reporter.log(ReportUtil.getOutputValidationReport(ouputValid));

		if (!OutputValidationUtil.publishOutputResult(ouputValid))
			throw new AdminTestException("Failed at output validation");

		// ── Step 7: Persist IDs for positive cases ──────────────────
		if (testCaseDTO.getTestCaseName().contains("_Pos")) {
			writeAutoGeneratedId(testCaseName, "UIN", uin);
			writeAutoGeneratedId(testCaseName, "RID", rid);
			logger.info("Persisted — UIN: " + uin + " | RID: " + rid);
		}
	}

	private String fetchUINWithRetry(String rid, String token) throws InterruptedException {
		String uin = null;
		for (int attempt = 1; attempt <= MAX_RETRIES; attempt++) {
			uin = fetchUINByRID(rid, token);
			if (uin != null && !uin.isEmpty()) {
				logger.info("UIN fetched on attempt " + attempt + ": " + uin);
				return uin;
			}
			logger.warn(
					"UIN not ready, attempt " + attempt + "/" + MAX_RETRIES + " — waiting " + WAIT_SECONDS + "s...");
			Thread.sleep(WAIT_SECONDS * 1000L);
		}
		return uin;
	}

	private String fetchUINByRID(String rid, String token) {
		try {
			Response ridResponse = RestClient.getRequestWithCookie(ApplnURI + IDREPO_RID_ENDPOINT + rid,
					MediaType.APPLICATION_JSON, MediaType.APPLICATION_JSON, COOKIENAME, token);

			logger.info("IDREPO response for RID [" + rid + "]: " + ridResponse.asString());
			return JsonPrecondtion.getValueFromJson(ridResponse.asString(), RESPONSE_IDENTITY_UIN);

		} catch (Exception e) {
			logger.error("Error fetching UIN for RID [" + rid + "]: " + e.getMessage());
			return null;
		}
	}

	@AfterMethod(alwaysRun = true)
	public void setResultTestName(ITestResult result) {
		try {
			Field method = TestResult.class.getDeclaredField("m_method");
			method.setAccessible(true);
			method.set(result, result.getMethod().clone());
			BaseTestMethod baseTestMethod = (BaseTestMethod) result.getMethod();
			Field f = baseTestMethod.getClass().getSuperclass().getDeclaredField("m_methodName");
			f.setAccessible(true);
			f.set(baseTestMethod, testCaseName);
		} catch (Exception e) {
			Reporter.log("Exception : " + e.getMessage());
		}
	}

	@AfterClass(alwaysRun = true)
	public void waittime() {
		try {
			logger.info("Waiting " + properties.getProperty("Delaytime") + " ms after UIN generation");
			Thread.sleep(Long.parseLong(properties.getProperty("Delaytime")));
		} catch (InterruptedException e) {
			Thread.currentThread().interrupt();
			logger.error("Interrupted in waittime: " + e.getMessage());
		} catch (Exception e) {

		}
	}
}